author:
  name: "Mustafa Said AÄŸca"
  social:
    github: "https://github.com/msagca"
    itch-io: "https://msagca.itch.io"
    linkedin: "https://linkedin.com/in/msagca"
    unity: "https://discussions.unity.com/u/msagca"
title: "msagca"
description: "A blog about programming and game development"
url: "https://msagca.github.io"
baseurl: ""
permalink: "/:title/"
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-paginate
paginate: 10
